version: "3"
services:
  ovpn_proxy:
    image: akirill0v/privoxy-socks5-openvpn
    build: .
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    # cloudflare DNS
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - ./openvpn-config:/app/ovpn/config
    environment:
      - OPENVPN_FILENAME=uk-london-aes128.ovpn
      - LOCAL_NETWORK=192.168.1.0/24
      - ONLINECHECK_DELAY=900
      - SOCKS_AUTHTYPE=2
      - SOCKS_USERNAME=proxy
      - SOCKS_PASSWORD=test123
    ports:
      - 8080:1080
    restart: always
