#!/bin/sh
sleep 10

# so return traffic that went through VPN works
gw=$(ip route | awk '/default/ {print $3}')
ip route add to ${LOCAL_NETWORK} via $gw dev eth0

# start
socks_proxy -a ${SOCKS_AUTHTYPE} -u ${SOCKS_USERNAME} -p ${SOCKS_PASSWORD}
